spring.application.name=loan-service
server.port=8081
logging.level.com.cognizant.loan=DEBUG

# Register with Eureka Discovery Server
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
