spring.application.name=greet-service
server.port=8082

# Register with Eureka Discovery Server
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
logging.level.com.cognizant.greetservice=DEBUG
